### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by alac1984** [yuki-uthman/virtual-echo.nvim#1]
This extension was working just fine in my Neovim, and suddenly it stopped working. Now I hit refresh, toggle and nothing happens. I didn't change anything in my setup that I can expect to cause this break, with the exception of my regular updates on Ubuntu. I cannot confirm that Ubuntu updated Neovim package or anything (I rarely read what is being installed on a `sudo apt upgrade`), can only say that right now I'm using Neovim 0.6.1 right from Ubuntu 22.04 `apt` official repository. 

I ran Neovim with V option to generate a runtime log and I saw that the keyboard commands are indeed calling the functions:

```
Executando BufWritePost Autocommands for "*.vim"
autocomando call vimpad#refresh()

chdir(/home/andre)
chdir(/home/andre/.vim/bundle/nvim-vimpad/autoload)
chdir(/home/andre)
linha 0: executando "/home/andre/.vim/bundle/nvim-vimpad/autoload/vimpad.vim"
fim da execução de /home/andre/.vim/bundle/nvim-vimpad/autoload/vimpad.vim
continuando em BufWritePost Autocommands for "*.vim"
Executando BufWritePost Autocommands for "*"
autocomando call s:reset_untracked_cache(0)
```
So, it's not something with the mapping, and (maybe?) not a update problem. Reading the log I can see vimpad executing (and no error between the execution lines, which I think is good). What could be the issue? I accept any tips on how can I debug this application in order to discover the problem. I really love this extension.

**Comment by alac1984** [comment]
The problem was that I changed the `nmap` in mapping `nnoremap` to `<Plugin>`, and I didn't know that `<Plugin>` doesn't work with `nnoremap`.

**Comment by yuki-uthman** [comment]
Oh I am sorry I did not check my email for a few days! 

I am glad it is working again! 

Thank you for liking it :)
